version: '3.8'
services:
  backend:
    build: ../../
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: qwe
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwe
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

volumes:
  db-data: